### ISSUE TITLE
TukUI 15.18 Statue Update issue

### ISSUE THREAD

**Issue by haohmaruxi** [sinaris/AsphyxiaUI---v6#19]
I started receiving this error once I updated from TukUI 15.17 to 15.18.

Date: 2012-09-15 22:43:51
ID: 1
Error occured in: Global
Count: 1
Message: ...\AsphyxiaUI\Unitframes\Layouts\Asphyxia\Asphyxia.lua line 507:
   attempt to index field 'Statue' (a nil value)
Debug:

   ...\AsphyxiaUI\Unitframes\Layouts\Asphyxia\Asphyxia.lua:507: in main chunk
Locals:
S = <table> {
 resolution = "1600x900"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:988
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:62
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 CheckCast = <function> defined =[C](?):-1
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\AddOns\AsphyxiaUI\Media\Fonts\Asphyxia.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:971
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C](?):-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:124
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:49
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 GetAsphyxiaUIVersion = "6.0.311"
 buffids = <table> {
 }
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:44
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:66
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 ShowPopup = <function> defined @Interface\AddOns\Tukui\core\popup.lua:84
 buttonspacing = 4
 SkinSlideBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:629
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:663
 buildtext = "16057"
 UpdateThreat = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1024
 HidePortrait = <function> defined @Interface\AddOns\Tukui\core\functions.lua:769
 SetGridGroupRole = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1043
 PostUpdateHealthRaid = <function> defined =[C](?):-1
 SkinFuncs = <table> {
 }
 UpdateName = <function> defined @Interface\AddOns\Tukui\core\functions.lua:965
 SkinTab = <function> defined @Interface\AddOns\Tukui\core\api.lua:475
 SkinRotateButton = <function> defined @Interface\AddOns\Tukui\core\api.lua:530
 IsPTRVersion = <function> defined @Interface\AddOns\Tukui\core\functions.lua:10
 SkinScrollBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:403
 client = "enUS"
 createAuraWatch = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1092
 build = 16057
 RGBToHex = <function> defined @Interface\AddOns\Tukui\core\functions.lua:234
 PostUpdatePower = <function> defined =[C](?):-1
 UTF = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:12
 StyleShift = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:141
 fadeIn = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:86
 SkinEditBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:547
 fadeOut = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:81
 countOffsets = <table> {
 }
 SetFontString = <function> defined @Interface\AddOns\Tukui\core\functions.lua:19
 Scale = <function> defined @Interface\AddOns\Tukui\core\api.lua:24
 PostUpdateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:713
 DataTextPosition = <function> defined @Interface\AddOns\Tukui\core\functions.lua:29
 MoveUIElements = <function> defined @Interface\AddOns\Tukui\core\move.lua:110
 StylePet = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:151
 level = 85
 update_alpha = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:74
 versionnumber = 15.18
 myrace = "Tauren"
 Delay = <functi
AddOns:
  Swatter, v5.14.5335 (KowariOnCrutches)
  AsphyxiaUI, v6.0.311
  AsphyxiaUIConfig, v6.0.311
  DBMCore, v
  Omen, v3.1.7
  Recount, v
  Tukui, v15.18
  TukuiConfigUI, v
  BlizRuntimeLib_enUS v5.0.5.50001 <us>
  (ck=d1)

**Comment by Slapaxx** [comment]
Did you make sure you updated to the latest Asphyxia because this issue was fixed after Tukui updated his UI

**Comment by haohmaruxi** [comment]
yeah, i managed to temporarily fix the problem by going to asphyxia.lua in layout and the layout/asphyxia folder and commenting out the statue lines starting on 507.

**Comment by sinaris** [comment]
You dont want to edit the AsphyxiaUI. Update Tukui instead of chaning the AsphyxiaUI code ...

**Comment by haohmaruxi** [comment]
my TukUI is version 15.18 and I updated to the latest git of AsphyxiaUI and am still getting this error on two of my characters, my warrior and my priest.

**Comment by haohmaruxi** [comment]
The error only started after 15.18, which was issued yesterday. 15.17 and below worked fine.

**Comment by Slapaxx** [comment]
I do not understand how you are getting the error, i play a DK, Warrior, Priest and i cannot reproduce this error with the latest updates. Please make sure your global style is set to asphyxia and one of the named layouts listed under the AsphyxiaUI menu tab when you open /tc menu.

**Comment by ottopatrick** [comment]
I had an issue yesterday with the Tukui Client too. The latest comments weren't in it, so try to download it manually on Tukui.org.

**Comment by haohmaruxi** [comment]
Updating manually through tukui.org seems to have fixed it. I originally used to client to update also. Thank you, and sorry for the trouble. ^^;;
